# Generated by Django 5.0.6 on 2024-08-07 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dilu', '0005_alter_dilu_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dilu',
            unique_together={('owner', 'name')},
        ),
    ]
