# Generated by Django 5.0.6 on 2024-07-08 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_admin_user(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    User = apps.get_model('user', 'User')

    default_user = User.objects.get(email='admin@admin.com')

    print(default_user)

    if default_user:
        Category.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(assign_admin_user)
    ]
