# Generated by Django 5.0.6 on 2024-07-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='updatd',
            new_name='updated',
        ),
    ]
