# Generated by Django 5.0.6 on 2024-07-16 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_updatd_expense_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
