# Generated by Django 5.0.6 on 2024-07-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['created']},
        ),
    ]
