# Generated by Django 5.0.6 on 2024-07-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created']},
        ),
    ]
